[package]
name = "ghidra-decompiler"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cxx = "1.0"
goblin = "0.8.0"

[build-dependencies]
bindgen = "0.65.1"
cxx-build = "1.0"
goblin = "0.8.0"
